services:
  - type: web
    name: saini-txt-direct
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/nikhilsainiop/Saini-txt-direct
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: API_ID
        sync: true
      - key: API_HASH
        sync: true
      - key: OWNER
        sync: true
      - key: CREDIT
        sync: true
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
